#!/bin/bash

database='tfcapi'
table='siri_vm_5'
loader='siri-vm-to-csv4.py'
load_pattern=''
work_mem='2GB'
maintenance_work_mem='2GB'

# Make this work on laptop and tfc servers
if [[ -d "${HOME}/icp/data/" ]]; then
    load_path="${HOME}/icp/data/sirivm_json/data_bin/${load_pattern}"
else
    load_path="/media/tfc/sirivm_json/data_bin/${load_pattern}"
fi

echo
echo "Loading data from ${load_path} into database ${database}, table ${table}"
echo

time psql -d "${database}" -e -X <<EOF

\timing on

SET work_mem TO '${work_mem}';
SET maintenance_work_mem TO '${maintenance_work_mem}';

BEGIN;

DROP TABLE IF EXISTS ${table} CASCADE;

CREATE TABLE ${table} (
    acp_id                   CHAR(20) NOT NULL,
    acp_lng                  DOUBLE PRECISION NOT NULL,
    acp_lat                  DOUBLE PRECISION NOT NULL,
    acp_ts                   BIGINT NOT NULL,
    location2d               GEOGRAPHY(POINT,4326) NOT NULL,
    location4d               GEOGRAPHY(POINTZM,4326) NOT NULL,
    info                     JSONB NOT NULL,
    acp_ts_date              DATE
   );

-- ---------------------------------------------------------------------
-- AUTO GENERATED BY make_partitions.py
-- ---------------------------------------------------------------------



-- 1507507200 - 1508112000 (2017-10-09T00:00:00+00:00 to 2017-10-16T00:00:00+00:00) 2017_41
CREATE TABLE ${table}_2017_41 (
    CHECK ( acp_ts >= 1507507200 and acp_ts < 1508112000 )
) INHERITS (${table});

-- 1508112000 - 1508716800 (2017-10-16T00:00:00+00:00 to 2017-10-23T00:00:00+00:00) 2017_42
CREATE TABLE ${table}_2017_42 (
    CHECK ( acp_ts >= 1508112000 and acp_ts < 1508716800 )
) INHERITS (${table});

-- 1508716800 - 1509321600 (2017-10-23T00:00:00+00:00 to 2017-10-30T00:00:00+00:00) 2017_43
CREATE TABLE ${table}_2017_43 (
    CHECK ( acp_ts >= 1508716800 and acp_ts < 1509321600 )
) INHERITS (${table});

-- 1509321600 - 1509926400 (2017-10-30T00:00:00+00:00 to 2017-11-06T00:00:00+00:00) 2017_44
CREATE TABLE ${table}_2017_44 (
    CHECK ( acp_ts >= 1509321600 and acp_ts < 1509926400 )
) INHERITS (${table});

-- 1509926400 - 1510531200 (2017-11-06T00:00:00+00:00 to 2017-11-13T00:00:00+00:00) 2017_45
CREATE TABLE ${table}_2017_45 (
    CHECK ( acp_ts >= 1509926400 and acp_ts < 1510531200 )
) INHERITS (${table});

-- 1510531200 - 1511136000 (2017-11-13T00:00:00+00:00 to 2017-11-20T00:00:00+00:00) 2017_46
CREATE TABLE ${table}_2017_46 (
    CHECK ( acp_ts >= 1510531200 and acp_ts < 1511136000 )
) INHERITS (${table});

-- 1511136000 - 1511740800 (2017-11-20T00:00:00+00:00 to 2017-11-27T00:00:00+00:00) 2017_47
CREATE TABLE ${table}_2017_47 (
    CHECK ( acp_ts >= 1511136000 and acp_ts < 1511740800 )
) INHERITS (${table});

-- 1511740800 - 1512345600 (2017-11-27T00:00:00+00:00 to 2017-12-04T00:00:00+00:00) 2017_48
CREATE TABLE ${table}_2017_48 (
    CHECK ( acp_ts >= 1511740800 and acp_ts < 1512345600 )
) INHERITS (${table});

-- 1512345600 - 1512950400 (2017-12-04T00:00:00+00:00 to 2017-12-11T00:00:00+00:00) 2017_49
CREATE TABLE ${table}_2017_49 (
    CHECK ( acp_ts >= 1512345600 and acp_ts < 1512950400 )
) INHERITS (${table});

-- 1512950400 - 1513555200 (2017-12-11T00:00:00+00:00 to 2017-12-18T00:00:00+00:00) 2017_50
CREATE TABLE ${table}_2017_50 (
    CHECK ( acp_ts >= 1512950400 and acp_ts < 1513555200 )
) INHERITS (${table});

-- 1513555200 - 1514160000 (2017-12-18T00:00:00+00:00 to 2017-12-25T00:00:00+00:00) 2017_51
CREATE TABLE ${table}_2017_51 (
    CHECK ( acp_ts >= 1513555200 and acp_ts < 1514160000 )
) INHERITS (${table});

-- 1514160000 - 1514764800 (2017-12-25T00:00:00+00:00 to 2018-01-01T00:00:00+00:00) 2017_52
CREATE TABLE ${table}_2017_52 (
    CHECK ( acp_ts >= 1514160000 and acp_ts < 1514764800 )
) INHERITS (${table});

-- 1514764800 - 1515369600 (2018-01-01T00:00:00+00:00 to 2018-01-08T00:00:00+00:00) 2018_01
CREATE TABLE ${table}_2018_01 (
    CHECK ( acp_ts >= 1514764800 and acp_ts < 1515369600 )
) INHERITS (${table});

-- 1515369600 - 1515974400 (2018-01-08T00:00:00+00:00 to 2018-01-15T00:00:00+00:00) 2018_02
CREATE TABLE ${table}_2018_02 (
    CHECK ( acp_ts >= 1515369600 and acp_ts < 1515974400 )
) INHERITS (${table});

-- 1515974400 - 1516579200 (2018-01-15T00:00:00+00:00 to 2018-01-22T00:00:00+00:00) 2018_03
CREATE TABLE ${table}_2018_03 (
    CHECK ( acp_ts >= 1515974400 and acp_ts < 1516579200 )
) INHERITS (${table});

-- 1516579200 - 1517184000 (2018-01-22T00:00:00+00:00 to 2018-01-29T00:00:00+00:00) 2018_04
CREATE TABLE ${table}_2018_04 (
    CHECK ( acp_ts >= 1516579200 and acp_ts < 1517184000 )
) INHERITS (${table});

-- 1517184000 - 1517788800 (2018-01-29T00:00:00+00:00 to 2018-02-05T00:00:00+00:00) 2018_05
CREATE TABLE ${table}_2018_05 (
    CHECK ( acp_ts >= 1517184000 and acp_ts < 1517788800 )
) INHERITS (${table});

-- 1517788800 - 1518393600 (2018-02-05T00:00:00+00:00 to 2018-02-12T00:00:00+00:00) 2018_06
CREATE TABLE ${table}_2018_06 (
    CHECK ( acp_ts >= 1517788800 and acp_ts < 1518393600 )
) INHERITS (${table});

-- 1518393600 - 1518998400 (2018-02-12T00:00:00+00:00 to 2018-02-19T00:00:00+00:00) 2018_07
CREATE TABLE ${table}_2018_07 (
    CHECK ( acp_ts >= 1518393600 and acp_ts < 1518998400 )
) INHERITS (${table});

-- 1518998400 - 1519603200 (2018-02-19T00:00:00+00:00 to 2018-02-26T00:00:00+00:00) 2018_08
CREATE TABLE ${table}_2018_08 (
    CHECK ( acp_ts >= 1518998400 and acp_ts < 1519603200 )
) INHERITS (${table});

-- 1519603200 - 1520208000 (2018-02-26T00:00:00+00:00 to 2018-03-05T00:00:00+00:00) 2018_09
CREATE TABLE ${table}_2018_09 (
    CHECK ( acp_ts >= 1519603200 and acp_ts < 1520208000 )
) INHERITS (${table});

-- 1520208000 - 1520812800 (2018-03-05T00:00:00+00:00 to 2018-03-12T00:00:00+00:00) 2018_10
CREATE TABLE ${table}_2018_10 (
    CHECK ( acp_ts >= 1520208000 and acp_ts < 1520812800 )
) INHERITS (${table});

-- 1520812800 - 1521417600 (2018-03-12T00:00:00+00:00 to 2018-03-19T00:00:00+00:00) 2018_11
CREATE TABLE ${table}_2018_11 (
    CHECK ( acp_ts >= 1520812800 and acp_ts < 1521417600 )
) INHERITS (${table});

-- 1521417600 - 1522022400 (2018-03-19T00:00:00+00:00 to 2018-03-26T00:00:00+00:00) 2018_12
CREATE TABLE ${table}_2018_12 (
    CHECK ( acp_ts >= 1521417600 and acp_ts < 1522022400 )
) INHERITS (${table});

-- 1522022400 - 1522627200 (2018-03-26T00:00:00+00:00 to 2018-04-02T00:00:00+00:00) 2018_13
CREATE TABLE ${table}_2018_13 (
    CHECK ( acp_ts >= 1522022400 and acp_ts < 1522627200 )
) INHERITS (${table});

-- 1522627200 - 1523232000 (2018-04-02T00:00:00+00:00 to 2018-04-09T00:00:00+00:00) 2018_14
CREATE TABLE ${table}_2018_14 (
    CHECK ( acp_ts >= 1522627200 and acp_ts < 1523232000 )
) INHERITS (${table});

-- 1523232000 - 1523836800 (2018-04-09T00:00:00+00:00 to 2018-04-16T00:00:00+00:00) 2018_15
CREATE TABLE ${table}_2018_15 (
    CHECK ( acp_ts >= 1523232000 and acp_ts < 1523836800 )
) INHERITS (${table});

-- 1523836800 - 1524441600 (2018-04-16T00:00:00+00:00 to 2018-04-23T00:00:00+00:00) 2018_16
CREATE TABLE ${table}_2018_16 (
    CHECK ( acp_ts >= 1523836800 and acp_ts < 1524441600 )
) INHERITS (${table});

-- 1524441600 - 1525046400 (2018-04-23T00:00:00+00:00 to 2018-04-30T00:00:00+00:00) 2018_17
CREATE TABLE ${table}_2018_17 (
    CHECK ( acp_ts >= 1524441600 and acp_ts < 1525046400 )
) INHERITS (${table});

-- 1525046400 - 1525651200 (2018-04-30T00:00:00+00:00 to 2018-05-07T00:00:00+00:00) 2018_18
CREATE TABLE ${table}_2018_18 (
    CHECK ( acp_ts >= 1525046400 and acp_ts < 1525651200 )
) INHERITS (${table});

-- 1525651200 - 1526256000 (2018-05-07T00:00:00+00:00 to 2018-05-14T00:00:00+00:00) 2018_19
CREATE TABLE ${table}_2018_19 (
    CHECK ( acp_ts >= 1525651200 and acp_ts < 1526256000 )
) INHERITS (${table});

-- 1526256000 - 1526860800 (2018-05-14T00:00:00+00:00 to 2018-05-21T00:00:00+00:00) 2018_20
CREATE TABLE ${table}_2018_20 (
    CHECK ( acp_ts >= 1526256000 and acp_ts < 1526860800 )
) INHERITS (${table});

-- 1526860800 - 1527465600 (2018-05-21T00:00:00+00:00 to 2018-05-28T00:00:00+00:00) 2018_21
CREATE TABLE ${table}_2018_21 (
    CHECK ( acp_ts >= 1526860800 and acp_ts < 1527465600 )
) INHERITS (${table});

-- 1527465600 - 1528070400 (2018-05-28T00:00:00+00:00 to 2018-06-04T00:00:00+00:00) 2018_22
CREATE TABLE ${table}_2018_22 (
    CHECK ( acp_ts >= 1527465600 and acp_ts < 1528070400 )
) INHERITS (${table});

-- 1528070400 - 1528675200 (2018-06-04T00:00:00+00:00 to 2018-06-11T00:00:00+00:00) 2018_23
CREATE TABLE ${table}_2018_23 (
    CHECK ( acp_ts >= 1528070400 and acp_ts < 1528675200 )
) INHERITS (${table});

-- 1528675200 - 1529280000 (2018-06-11T00:00:00+00:00 to 2018-06-18T00:00:00+00:00) 2018_24
CREATE TABLE ${table}_2018_24 (
    CHECK ( acp_ts >= 1528675200 and acp_ts < 1529280000 )
) INHERITS (${table});

-- 1529280000 - 1529884800 (2018-06-18T00:00:00+00:00 to 2018-06-25T00:00:00+00:00) 2018_25
CREATE TABLE ${table}_2018_25 (
    CHECK ( acp_ts >= 1529280000 and acp_ts < 1529884800 )
) INHERITS (${table});

-- 1529884800 - 1530489600 (2018-06-25T00:00:00+00:00 to 2018-07-02T00:00:00+00:00) 2018_26
CREATE TABLE ${table}_2018_26 (
    CHECK ( acp_ts >= 1529884800 and acp_ts < 1530489600 )
) INHERITS (${table});

-- 1530489600 - 1531094400 (2018-07-02T00:00:00+00:00 to 2018-07-09T00:00:00+00:00) 2018_27
CREATE TABLE ${table}_2018_27 (
    CHECK ( acp_ts >= 1530489600 and acp_ts < 1531094400 )
) INHERITS (${table});

-- 1531094400 - 1531699200 (2018-07-09T00:00:00+00:00 to 2018-07-16T00:00:00+00:00) 2018_28
CREATE TABLE ${table}_2018_28 (
    CHECK ( acp_ts >= 1531094400 and acp_ts < 1531699200 )
) INHERITS (${table});

-- 1531699200 - 1532304000 (2018-07-16T00:00:00+00:00 to 2018-07-23T00:00:00+00:00) 2018_29
CREATE TABLE ${table}_2018_29 (
    CHECK ( acp_ts >= 1531699200 and acp_ts < 1532304000 )
) INHERITS (${table});

-- 1532304000 - 1532908800 (2018-07-23T00:00:00+00:00 to 2018-07-30T00:00:00+00:00) 2018_30
CREATE TABLE ${table}_2018_30 (
    CHECK ( acp_ts >= 1532304000 and acp_ts < 1532908800 )
) INHERITS (${table});

-- 1532908800 - 1533513600 (2018-07-30T00:00:00+00:00 to 2018-08-06T00:00:00+00:00) 2018_31
CREATE TABLE ${table}_2018_31 (
    CHECK ( acp_ts >= 1532908800 and acp_ts < 1533513600 )
) INHERITS (${table});

-- 1533513600 - 1534118400 (2018-08-06T00:00:00+00:00 to 2018-08-13T00:00:00+00:00) 2018_32
CREATE TABLE ${table}_2018_32 (
    CHECK ( acp_ts >= 1533513600 and acp_ts < 1534118400 )
) INHERITS (${table});

-- 1534118400 - 1534723200 (2018-08-13T00:00:00+00:00 to 2018-08-20T00:00:00+00:00) 2018_33
CREATE TABLE ${table}_2018_33 (
    CHECK ( acp_ts >= 1534118400 and acp_ts < 1534723200 )
) INHERITS (${table});

-- 1534723200 - 1535328000 (2018-08-20T00:00:00+00:00 to 2018-08-27T00:00:00+00:00) 2018_34
CREATE TABLE ${table}_2018_34 (
    CHECK ( acp_ts >= 1534723200 and acp_ts < 1535328000 )
) INHERITS (${table});

-- 1535328000 - 1535932800 (2018-08-27T00:00:00+00:00 to 2018-09-03T00:00:00+00:00) 2018_35
CREATE TABLE ${table}_2018_35 (
    CHECK ( acp_ts >= 1535328000 and acp_ts < 1535932800 )
) INHERITS (${table});

-- 1535932800 - 1536537600 (2018-09-03T00:00:00+00:00 to 2018-09-10T00:00:00+00:00) 2018_36
CREATE TABLE ${table}_2018_36 (
    CHECK ( acp_ts >= 1535932800 and acp_ts < 1536537600 )
) INHERITS (${table});

-- 1536537600 - 1537142400 (2018-09-10T00:00:00+00:00 to 2018-09-17T00:00:00+00:00) 2018_37
CREATE TABLE ${table}_2018_37 (
    CHECK ( acp_ts >= 1536537600 and acp_ts < 1537142400 )
) INHERITS (${table});

-- 1537142400 - 1537747200 (2018-09-17T00:00:00+00:00 to 2018-09-24T00:00:00+00:00) 2018_38
CREATE TABLE ${table}_2018_38 (
    CHECK ( acp_ts >= 1537142400 and acp_ts < 1537747200 )
) INHERITS (${table});

-- 1537747200 - 1538352000 (2018-09-24T00:00:00+00:00 to 2018-10-01T00:00:00+00:00) 2018_39
CREATE TABLE ${table}_2018_39 (
    CHECK ( acp_ts >= 1537747200 and acp_ts < 1538352000 )
) INHERITS (${table});

-- 1538352000 - 1538956800 (2018-10-01T00:00:00+00:00 to 2018-10-08T00:00:00+00:00) 2018_40
CREATE TABLE ${table}_2018_40 (
    CHECK ( acp_ts >= 1538352000 and acp_ts < 1538956800 )
) INHERITS (${table});

-- 1538956800 - 1539561600 (2018-10-08T00:00:00+00:00 to 2018-10-15T00:00:00+00:00) 2018_41
CREATE TABLE ${table}_2018_41 (
    CHECK ( acp_ts >= 1538956800 and acp_ts < 1539561600 )
) INHERITS (${table});

-- 1539561600 - 1540166400 (2018-10-15T00:00:00+00:00 to 2018-10-22T00:00:00+00:00) 2018_42
CREATE TABLE ${table}_2018_42 (
    CHECK ( acp_ts >= 1539561600 and acp_ts < 1540166400 )
) INHERITS (${table});

-- 1540166400 - 1540771200 (2018-10-22T00:00:00+00:00 to 2018-10-29T00:00:00+00:00) 2018_43
CREATE TABLE ${table}_2018_43 (
    CHECK ( acp_ts >= 1540166400 and acp_ts < 1540771200 )
) INHERITS (${table});

-- 1540771200 - 1541376000 (2018-10-29T00:00:00+00:00 to 2018-11-05T00:00:00+00:00) 2018_44
CREATE TABLE ${table}_2018_44 (
    CHECK ( acp_ts >= 1540771200 and acp_ts < 1541376000 )
) INHERITS (${table});

-- 1541376000 - 1541980800 (2018-11-05T00:00:00+00:00 to 2018-11-12T00:00:00+00:00) 2018_45
CREATE TABLE ${table}_2018_45 (
    CHECK ( acp_ts >= 1541376000 and acp_ts < 1541980800 )
) INHERITS (${table});

-- 1541980800 - 1542585600 (2018-11-12T00:00:00+00:00 to 2018-11-19T00:00:00+00:00) 2018_46
CREATE TABLE ${table}_2018_46 (
    CHECK ( acp_ts >= 1541980800 and acp_ts < 1542585600 )
) INHERITS (${table});

-- 1542585600 - 1543190400 (2018-11-19T00:00:00+00:00 to 2018-11-26T00:00:00+00:00) 2018_47
CREATE TABLE ${table}_2018_47 (
    CHECK ( acp_ts >= 1542585600 and acp_ts < 1543190400 )
) INHERITS (${table});

-- 1543190400 - 1543795200 (2018-11-26T00:00:00+00:00 to 2018-12-03T00:00:00+00:00) 2018_48
CREATE TABLE ${table}_2018_48 (
    CHECK ( acp_ts >= 1543190400 and acp_ts < 1543795200 )
) INHERITS (${table});

-- 1543795200 - 1544400000 (2018-12-03T00:00:00+00:00 to 2018-12-10T00:00:00+00:00) 2018_49
CREATE TABLE ${table}_2018_49 (
    CHECK ( acp_ts >= 1543795200 and acp_ts < 1544400000 )
) INHERITS (${table});

-- 1544400000 - 1545004800 (2018-12-10T00:00:00+00:00 to 2018-12-17T00:00:00+00:00) 2018_50
CREATE TABLE ${table}_2018_50 (
    CHECK ( acp_ts >= 1544400000 and acp_ts < 1545004800 )
) INHERITS (${table});

-- 1545004800 - 1545609600 (2018-12-17T00:00:00+00:00 to 2018-12-24T00:00:00+00:00) 2018_51
CREATE TABLE ${table}_2018_51 (
    CHECK ( acp_ts >= 1545004800 and acp_ts < 1545609600 )
) INHERITS (${table});

-- 1545609600 - 1546214400 (2018-12-24T00:00:00+00:00 to 2018-12-31T00:00:00+00:00) 2018_52
CREATE TABLE ${table}_2018_52 (
    CHECK ( acp_ts >= 1545609600 and acp_ts < 1546214400 )
) INHERITS (${table});


CREATE OR REPLACE FUNCTION ${table}_insert_trigger()
RETURNS TRIGGER AS \$\$
BEGIN
    IF ( NEW.acp_ts >= 1507507200 AND
            NEW.acp_ts < 1508112000 ) THEN
       INSERT INTO ${table}_2017_41 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1508112000 AND
            NEW.acp_ts < 1508716800 ) THEN
       INSERT INTO ${table}_2017_42 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1508716800 AND
            NEW.acp_ts < 1509321600 ) THEN
       INSERT INTO ${table}_2017_43 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1509321600 AND
            NEW.acp_ts < 1509926400 ) THEN
       INSERT INTO ${table}_2017_44 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1509926400 AND
            NEW.acp_ts < 1510531200 ) THEN
       INSERT INTO ${table}_2017_45 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1510531200 AND
            NEW.acp_ts < 1511136000 ) THEN
       INSERT INTO ${table}_2017_46 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1511136000 AND
            NEW.acp_ts < 1511740800 ) THEN
       INSERT INTO ${table}_2017_47 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1511740800 AND
            NEW.acp_ts < 1512345600 ) THEN
       INSERT INTO ${table}_2017_48 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1512345600 AND
            NEW.acp_ts < 1512950400 ) THEN
       INSERT INTO ${table}_2017_49 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1512950400 AND
            NEW.acp_ts < 1513555200 ) THEN
       INSERT INTO ${table}_2017_50 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1513555200 AND
            NEW.acp_ts < 1514160000 ) THEN
       INSERT INTO ${table}_2017_51 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1514160000 AND
            NEW.acp_ts < 1514764800 ) THEN
       INSERT INTO ${table}_2017_52 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1514764800 AND
            NEW.acp_ts < 1515369600 ) THEN
       INSERT INTO ${table}_2018_01 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1515369600 AND
            NEW.acp_ts < 1515974400 ) THEN
       INSERT INTO ${table}_2018_02 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1515974400 AND
            NEW.acp_ts < 1516579200 ) THEN
       INSERT INTO ${table}_2018_03 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1516579200 AND
            NEW.acp_ts < 1517184000 ) THEN
       INSERT INTO ${table}_2018_04 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1517184000 AND
            NEW.acp_ts < 1517788800 ) THEN
       INSERT INTO ${table}_2018_05 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1517788800 AND
            NEW.acp_ts < 1518393600 ) THEN
       INSERT INTO ${table}_2018_06 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1518393600 AND
            NEW.acp_ts < 1518998400 ) THEN
       INSERT INTO ${table}_2018_07 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1518998400 AND
            NEW.acp_ts < 1519603200 ) THEN
       INSERT INTO ${table}_2018_08 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1519603200 AND
            NEW.acp_ts < 1520208000 ) THEN
       INSERT INTO ${table}_2018_09 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1520208000 AND
            NEW.acp_ts < 1520812800 ) THEN
       INSERT INTO ${table}_2018_10 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1520812800 AND
            NEW.acp_ts < 1521417600 ) THEN
       INSERT INTO ${table}_2018_11 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1521417600 AND
            NEW.acp_ts < 1522022400 ) THEN
       INSERT INTO ${table}_2018_12 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1522022400 AND
            NEW.acp_ts < 1522627200 ) THEN
       INSERT INTO ${table}_2018_13 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1522627200 AND
            NEW.acp_ts < 1523232000 ) THEN
       INSERT INTO ${table}_2018_14 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1523232000 AND
            NEW.acp_ts < 1523836800 ) THEN
       INSERT INTO ${table}_2018_15 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1523836800 AND
            NEW.acp_ts < 1524441600 ) THEN
       INSERT INTO ${table}_2018_16 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1524441600 AND
            NEW.acp_ts < 1525046400 ) THEN
       INSERT INTO ${table}_2018_17 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1525046400 AND
            NEW.acp_ts < 1525651200 ) THEN
       INSERT INTO ${table}_2018_18 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1525651200 AND
            NEW.acp_ts < 1526256000 ) THEN
       INSERT INTO ${table}_2018_19 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1526256000 AND
            NEW.acp_ts < 1526860800 ) THEN
       INSERT INTO ${table}_2018_20 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1526860800 AND
            NEW.acp_ts < 1527465600 ) THEN
       INSERT INTO ${table}_2018_21 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1527465600 AND
            NEW.acp_ts < 1528070400 ) THEN
       INSERT INTO ${table}_2018_22 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1528070400 AND
            NEW.acp_ts < 1528675200 ) THEN
       INSERT INTO ${table}_2018_23 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1528675200 AND
            NEW.acp_ts < 1529280000 ) THEN
       INSERT INTO ${table}_2018_24 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1529280000 AND
            NEW.acp_ts < 1529884800 ) THEN
       INSERT INTO ${table}_2018_25 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1529884800 AND
            NEW.acp_ts < 1530489600 ) THEN
       INSERT INTO ${table}_2018_26 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1530489600 AND
            NEW.acp_ts < 1531094400 ) THEN
       INSERT INTO ${table}_2018_27 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1531094400 AND
            NEW.acp_ts < 1531699200 ) THEN
       INSERT INTO ${table}_2018_28 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1531699200 AND
            NEW.acp_ts < 1532304000 ) THEN
       INSERT INTO ${table}_2018_29 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1532304000 AND
            NEW.acp_ts < 1532908800 ) THEN
       INSERT INTO ${table}_2018_30 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1532908800 AND
            NEW.acp_ts < 1533513600 ) THEN
       INSERT INTO ${table}_2018_31 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1533513600 AND
            NEW.acp_ts < 1534118400 ) THEN
       INSERT INTO ${table}_2018_32 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1534118400 AND
            NEW.acp_ts < 1534723200 ) THEN
       INSERT INTO ${table}_2018_33 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1534723200 AND
            NEW.acp_ts < 1535328000 ) THEN
       INSERT INTO ${table}_2018_34 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1535328000 AND
            NEW.acp_ts < 1535932800 ) THEN
       INSERT INTO ${table}_2018_35 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1535932800 AND
            NEW.acp_ts < 1536537600 ) THEN
       INSERT INTO ${table}_2018_36 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1536537600 AND
            NEW.acp_ts < 1537142400 ) THEN
       INSERT INTO ${table}_2018_37 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1537142400 AND
            NEW.acp_ts < 1537747200 ) THEN
       INSERT INTO ${table}_2018_38 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1537747200 AND
            NEW.acp_ts < 1538352000 ) THEN
       INSERT INTO ${table}_2018_39 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1538352000 AND
            NEW.acp_ts < 1538956800 ) THEN
       INSERT INTO ${table}_2018_40 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1538956800 AND
            NEW.acp_ts < 1539561600 ) THEN
       INSERT INTO ${table}_2018_41 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1539561600 AND
            NEW.acp_ts < 1540166400 ) THEN
       INSERT INTO ${table}_2018_42 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1540166400 AND
            NEW.acp_ts < 1540771200 ) THEN
       INSERT INTO ${table}_2018_43 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1540771200 AND
            NEW.acp_ts < 1541376000 ) THEN
       INSERT INTO ${table}_2018_44 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1541376000 AND
            NEW.acp_ts < 1541980800 ) THEN
       INSERT INTO ${table}_2018_45 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1541980800 AND
            NEW.acp_ts < 1542585600 ) THEN
       INSERT INTO ${table}_2018_46 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1542585600 AND
            NEW.acp_ts < 1543190400 ) THEN
       INSERT INTO ${table}_2018_47 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1543190400 AND
            NEW.acp_ts < 1543795200 ) THEN
       INSERT INTO ${table}_2018_48 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1543795200 AND
            NEW.acp_ts < 1544400000 ) THEN
       INSERT INTO ${table}_2018_49 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1544400000 AND
            NEW.acp_ts < 1545004800 ) THEN
       INSERT INTO ${table}_2018_50 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1545004800 AND
            NEW.acp_ts < 1545609600 ) THEN
       INSERT INTO ${table}_2018_51 VALUES (NEW.*);
    ELSIF ( NEW.acp_ts >= 1545609600 AND
            NEW.acp_ts < 1546214400 ) THEN
       INSERT INTO ${table}_2018_52 VALUES (NEW.*);
    ELSE
        RAISE EXCEPTION 'Date out of range.  Fix the ${table}_insert_trigger() function!';
    END IF;
    RETURN NULL;
END;
\$\$
LANGUAGE plpgsql;

CREATE TRIGGER insert_${table}_trigger
    BEFORE INSERT ON ${table}
    FOR EACH ROW EXECUTE PROCEDURE ${table}_insert_trigger();

\copy ${table} (acp_id, acp_lng, acp_lat, acp_ts, location2d, location4d, info) FROM PROGRAM './"${loader}" "${load_path}"' (FORMAT CSV, FREEZE TRUE)

CREATE INDEX ${table}_2017_41_acp_id ON ${table}_2017_41 (acp_id);
CREATE INDEX ${table}_2017_41_acp_lng ON ${table}_2017_41 (acp_lng);
CREATE INDEX ${table}_2017_41_acp_lat ON ${table}_2017_41 (acp_lat);
CREATE INDEX ${table}_2017_41_acp_ts ON ${table}_2017_41 (acp_ts);
CREATE INDEX ${table}_2017_41_location2d on ${table}_2017_41 USING GIST (location2d);
CREATE INDEX ${table}_2017_41_location2d_geom on ${table}_2017_41 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2017_41_location4d on ${table}_2017_41 USING GIST (location4d);
CREATE INDEX ${table}_2017_41_location4d_geom_nd on ${table}_2017_41 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2017_41_info ON ${table}_2017_41 USING GIN (info);

CREATE INDEX ${table}_2017_42_acp_id ON ${table}_2017_42 (acp_id);
CREATE INDEX ${table}_2017_42_acp_lng ON ${table}_2017_42 (acp_lng);
CREATE INDEX ${table}_2017_42_acp_lat ON ${table}_2017_42 (acp_lat);
CREATE INDEX ${table}_2017_42_acp_ts ON ${table}_2017_42 (acp_ts);
CREATE INDEX ${table}_2017_42_location2d on ${table}_2017_42 USING GIST (location2d);
CREATE INDEX ${table}_2017_42_location2d_geom on ${table}_2017_42 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2017_42_location4d on ${table}_2017_42 USING GIST (location4d);
CREATE INDEX ${table}_2017_42_location4d_geom_nd on ${table}_2017_42 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2017_42_info ON ${table}_2017_42 USING GIN (info);

CREATE INDEX ${table}_2017_43_acp_id ON ${table}_2017_43 (acp_id);
CREATE INDEX ${table}_2017_43_acp_lng ON ${table}_2017_43 (acp_lng);
CREATE INDEX ${table}_2017_43_acp_lat ON ${table}_2017_43 (acp_lat);
CREATE INDEX ${table}_2017_43_acp_ts ON ${table}_2017_43 (acp_ts);
CREATE INDEX ${table}_2017_43_location2d on ${table}_2017_43 USING GIST (location2d);
CREATE INDEX ${table}_2017_43_location2d_geom on ${table}_2017_43 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2017_43_location4d on ${table}_2017_43 USING GIST (location4d);
CREATE INDEX ${table}_2017_43_location4d_geom_nd on ${table}_2017_43 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2017_43_info ON ${table}_2017_43 USING GIN (info);

CREATE INDEX ${table}_2017_44_acp_id ON ${table}_2017_44 (acp_id);
CREATE INDEX ${table}_2017_44_acp_lng ON ${table}_2017_44 (acp_lng);
CREATE INDEX ${table}_2017_44_acp_lat ON ${table}_2017_44 (acp_lat);
CREATE INDEX ${table}_2017_44_acp_ts ON ${table}_2017_44 (acp_ts);
CREATE INDEX ${table}_2017_44_location2d on ${table}_2017_44 USING GIST (location2d);
CREATE INDEX ${table}_2017_44_location2d_geom on ${table}_2017_44 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2017_44_location4d on ${table}_2017_44 USING GIST (location4d);
CREATE INDEX ${table}_2017_44_location4d_geom_nd on ${table}_2017_44 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2017_44_info ON ${table}_2017_44 USING GIN (info);

CREATE INDEX ${table}_2017_45_acp_id ON ${table}_2017_45 (acp_id);
CREATE INDEX ${table}_2017_45_acp_lng ON ${table}_2017_45 (acp_lng);
CREATE INDEX ${table}_2017_45_acp_lat ON ${table}_2017_45 (acp_lat);
CREATE INDEX ${table}_2017_45_acp_ts ON ${table}_2017_45 (acp_ts);
CREATE INDEX ${table}_2017_45_location2d on ${table}_2017_45 USING GIST (location2d);
CREATE INDEX ${table}_2017_45_location2d_geom on ${table}_2017_45 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2017_45_location4d on ${table}_2017_45 USING GIST (location4d);
CREATE INDEX ${table}_2017_45_location4d_geom_nd on ${table}_2017_45 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2017_45_info ON ${table}_2017_45 USING GIN (info);

CREATE INDEX ${table}_2017_46_acp_id ON ${table}_2017_46 (acp_id);
CREATE INDEX ${table}_2017_46_acp_lng ON ${table}_2017_46 (acp_lng);
CREATE INDEX ${table}_2017_46_acp_lat ON ${table}_2017_46 (acp_lat);
CREATE INDEX ${table}_2017_46_acp_ts ON ${table}_2017_46 (acp_ts);
CREATE INDEX ${table}_2017_46_location2d on ${table}_2017_46 USING GIST (location2d);
CREATE INDEX ${table}_2017_46_location2d_geom on ${table}_2017_46 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2017_46_location4d on ${table}_2017_46 USING GIST (location4d);
CREATE INDEX ${table}_2017_46_location4d_geom_nd on ${table}_2017_46 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2017_46_info ON ${table}_2017_46 USING GIN (info);

CREATE INDEX ${table}_2017_47_acp_id ON ${table}_2017_47 (acp_id);
CREATE INDEX ${table}_2017_47_acp_lng ON ${table}_2017_47 (acp_lng);
CREATE INDEX ${table}_2017_47_acp_lat ON ${table}_2017_47 (acp_lat);
CREATE INDEX ${table}_2017_47_acp_ts ON ${table}_2017_47 (acp_ts);
CREATE INDEX ${table}_2017_47_location2d on ${table}_2017_47 USING GIST (location2d);
CREATE INDEX ${table}_2017_47_location2d_geom on ${table}_2017_47 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2017_47_location4d on ${table}_2017_47 USING GIST (location4d);
CREATE INDEX ${table}_2017_47_location4d_geom_nd on ${table}_2017_47 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2017_47_info ON ${table}_2017_47 USING GIN (info);

CREATE INDEX ${table}_2017_48_acp_id ON ${table}_2017_48 (acp_id);
CREATE INDEX ${table}_2017_48_acp_lng ON ${table}_2017_48 (acp_lng);
CREATE INDEX ${table}_2017_48_acp_lat ON ${table}_2017_48 (acp_lat);
CREATE INDEX ${table}_2017_48_acp_ts ON ${table}_2017_48 (acp_ts);
CREATE INDEX ${table}_2017_48_location2d on ${table}_2017_48 USING GIST (location2d);
CREATE INDEX ${table}_2017_48_location2d_geom on ${table}_2017_48 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2017_48_location4d on ${table}_2017_48 USING GIST (location4d);
CREATE INDEX ${table}_2017_48_location4d_geom_nd on ${table}_2017_48 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2017_48_info ON ${table}_2017_48 USING GIN (info);

CREATE INDEX ${table}_2017_49_acp_id ON ${table}_2017_49 (acp_id);
CREATE INDEX ${table}_2017_49_acp_lng ON ${table}_2017_49 (acp_lng);
CREATE INDEX ${table}_2017_49_acp_lat ON ${table}_2017_49 (acp_lat);
CREATE INDEX ${table}_2017_49_acp_ts ON ${table}_2017_49 (acp_ts);
CREATE INDEX ${table}_2017_49_location2d on ${table}_2017_49 USING GIST (location2d);
CREATE INDEX ${table}_2017_49_location2d_geom on ${table}_2017_49 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2017_49_location4d on ${table}_2017_49 USING GIST (location4d);
CREATE INDEX ${table}_2017_49_location4d_geom_nd on ${table}_2017_49 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2017_49_info ON ${table}_2017_49 USING GIN (info);

CREATE INDEX ${table}_2017_50_acp_id ON ${table}_2017_50 (acp_id);
CREATE INDEX ${table}_2017_50_acp_lng ON ${table}_2017_50 (acp_lng);
CREATE INDEX ${table}_2017_50_acp_lat ON ${table}_2017_50 (acp_lat);
CREATE INDEX ${table}_2017_50_acp_ts ON ${table}_2017_50 (acp_ts);
CREATE INDEX ${table}_2017_50_location2d on ${table}_2017_50 USING GIST (location2d);
CREATE INDEX ${table}_2017_50_location2d_geom on ${table}_2017_50 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2017_50_location4d on ${table}_2017_50 USING GIST (location4d);
CREATE INDEX ${table}_2017_50_location4d_geom_nd on ${table}_2017_50 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2017_50_info ON ${table}_2017_50 USING GIN (info);

CREATE INDEX ${table}_2017_51_acp_id ON ${table}_2017_51 (acp_id);
CREATE INDEX ${table}_2017_51_acp_lng ON ${table}_2017_51 (acp_lng);
CREATE INDEX ${table}_2017_51_acp_lat ON ${table}_2017_51 (acp_lat);
CREATE INDEX ${table}_2017_51_acp_ts ON ${table}_2017_51 (acp_ts);
CREATE INDEX ${table}_2017_51_location2d on ${table}_2017_51 USING GIST (location2d);
CREATE INDEX ${table}_2017_51_location2d_geom on ${table}_2017_51 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2017_51_location4d on ${table}_2017_51 USING GIST (location4d);
CREATE INDEX ${table}_2017_51_location4d_geom_nd on ${table}_2017_51 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2017_51_info ON ${table}_2017_51 USING GIN (info);

CREATE INDEX ${table}_2017_52_acp_id ON ${table}_2017_52 (acp_id);
CREATE INDEX ${table}_2017_52_acp_lng ON ${table}_2017_52 (acp_lng);
CREATE INDEX ${table}_2017_52_acp_lat ON ${table}_2017_52 (acp_lat);
CREATE INDEX ${table}_2017_52_acp_ts ON ${table}_2017_52 (acp_ts);
CREATE INDEX ${table}_2017_52_location2d on ${table}_2017_52 USING GIST (location2d);
CREATE INDEX ${table}_2017_52_location2d_geom on ${table}_2017_52 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2017_52_location4d on ${table}_2017_52 USING GIST (location4d);
CREATE INDEX ${table}_2017_52_location4d_geom_nd on ${table}_2017_52 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2017_52_info ON ${table}_2017_52 USING GIN (info);

CREATE INDEX ${table}_2018_01_acp_id ON ${table}_2018_01 (acp_id);
CREATE INDEX ${table}_2018_01_acp_lng ON ${table}_2018_01 (acp_lng);
CREATE INDEX ${table}_2018_01_acp_lat ON ${table}_2018_01 (acp_lat);
CREATE INDEX ${table}_2018_01_acp_ts ON ${table}_2018_01 (acp_ts);
CREATE INDEX ${table}_2018_01_location2d on ${table}_2018_01 USING GIST (location2d);
CREATE INDEX ${table}_2018_01_location2d_geom on ${table}_2018_01 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_01_location4d on ${table}_2018_01 USING GIST (location4d);
CREATE INDEX ${table}_2018_01_location4d_geom_nd on ${table}_2018_01 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_01_info ON ${table}_2018_01 USING GIN (info);

CREATE INDEX ${table}_2018_02_acp_id ON ${table}_2018_02 (acp_id);
CREATE INDEX ${table}_2018_02_acp_lng ON ${table}_2018_02 (acp_lng);
CREATE INDEX ${table}_2018_02_acp_lat ON ${table}_2018_02 (acp_lat);
CREATE INDEX ${table}_2018_02_acp_ts ON ${table}_2018_02 (acp_ts);
CREATE INDEX ${table}_2018_02_location2d on ${table}_2018_02 USING GIST (location2d);
CREATE INDEX ${table}_2018_02_location2d_geom on ${table}_2018_02 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_02_location4d on ${table}_2018_02 USING GIST (location4d);
CREATE INDEX ${table}_2018_02_location4d_geom_nd on ${table}_2018_02 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_02_info ON ${table}_2018_02 USING GIN (info);

CREATE INDEX ${table}_2018_03_acp_id ON ${table}_2018_03 (acp_id);
CREATE INDEX ${table}_2018_03_acp_lng ON ${table}_2018_03 (acp_lng);
CREATE INDEX ${table}_2018_03_acp_lat ON ${table}_2018_03 (acp_lat);
CREATE INDEX ${table}_2018_03_acp_ts ON ${table}_2018_03 (acp_ts);
CREATE INDEX ${table}_2018_03_location2d on ${table}_2018_03 USING GIST (location2d);
CREATE INDEX ${table}_2018_03_location2d_geom on ${table}_2018_03 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_03_location4d on ${table}_2018_03 USING GIST (location4d);
CREATE INDEX ${table}_2018_03_location4d_geom_nd on ${table}_2018_03 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_03_info ON ${table}_2018_03 USING GIN (info);

CREATE INDEX ${table}_2018_04_acp_id ON ${table}_2018_04 (acp_id);
CREATE INDEX ${table}_2018_04_acp_lng ON ${table}_2018_04 (acp_lng);
CREATE INDEX ${table}_2018_04_acp_lat ON ${table}_2018_04 (acp_lat);
CREATE INDEX ${table}_2018_04_acp_ts ON ${table}_2018_04 (acp_ts);
CREATE INDEX ${table}_2018_04_location2d on ${table}_2018_04 USING GIST (location2d);
CREATE INDEX ${table}_2018_04_location2d_geom on ${table}_2018_04 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_04_location4d on ${table}_2018_04 USING GIST (location4d);
CREATE INDEX ${table}_2018_04_location4d_geom_nd on ${table}_2018_04 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_04_info ON ${table}_2018_04 USING GIN (info);

CREATE INDEX ${table}_2018_05_acp_id ON ${table}_2018_05 (acp_id);
CREATE INDEX ${table}_2018_05_acp_lng ON ${table}_2018_05 (acp_lng);
CREATE INDEX ${table}_2018_05_acp_lat ON ${table}_2018_05 (acp_lat);
CREATE INDEX ${table}_2018_05_acp_ts ON ${table}_2018_05 (acp_ts);
CREATE INDEX ${table}_2018_05_location2d on ${table}_2018_05 USING GIST (location2d);
CREATE INDEX ${table}_2018_05_location2d_geom on ${table}_2018_05 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_05_location4d on ${table}_2018_05 USING GIST (location4d);
CREATE INDEX ${table}_2018_05_location4d_geom_nd on ${table}_2018_05 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_05_info ON ${table}_2018_05 USING GIN (info);

CREATE INDEX ${table}_2018_06_acp_id ON ${table}_2018_06 (acp_id);
CREATE INDEX ${table}_2018_06_acp_lng ON ${table}_2018_06 (acp_lng);
CREATE INDEX ${table}_2018_06_acp_lat ON ${table}_2018_06 (acp_lat);
CREATE INDEX ${table}_2018_06_acp_ts ON ${table}_2018_06 (acp_ts);
CREATE INDEX ${table}_2018_06_location2d on ${table}_2018_06 USING GIST (location2d);
CREATE INDEX ${table}_2018_06_location2d_geom on ${table}_2018_06 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_06_location4d on ${table}_2018_06 USING GIST (location4d);
CREATE INDEX ${table}_2018_06_location4d_geom_nd on ${table}_2018_06 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_06_info ON ${table}_2018_06 USING GIN (info);

CREATE INDEX ${table}_2018_07_acp_id ON ${table}_2018_07 (acp_id);
CREATE INDEX ${table}_2018_07_acp_lng ON ${table}_2018_07 (acp_lng);
CREATE INDEX ${table}_2018_07_acp_lat ON ${table}_2018_07 (acp_lat);
CREATE INDEX ${table}_2018_07_acp_ts ON ${table}_2018_07 (acp_ts);
CREATE INDEX ${table}_2018_07_location2d on ${table}_2018_07 USING GIST (location2d);
CREATE INDEX ${table}_2018_07_location2d_geom on ${table}_2018_07 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_07_location4d on ${table}_2018_07 USING GIST (location4d);
CREATE INDEX ${table}_2018_07_location4d_geom_nd on ${table}_2018_07 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_07_info ON ${table}_2018_07 USING GIN (info);

CREATE INDEX ${table}_2018_08_acp_id ON ${table}_2018_08 (acp_id);
CREATE INDEX ${table}_2018_08_acp_lng ON ${table}_2018_08 (acp_lng);
CREATE INDEX ${table}_2018_08_acp_lat ON ${table}_2018_08 (acp_lat);
CREATE INDEX ${table}_2018_08_acp_ts ON ${table}_2018_08 (acp_ts);
CREATE INDEX ${table}_2018_08_location2d on ${table}_2018_08 USING GIST (location2d);
CREATE INDEX ${table}_2018_08_location2d_geom on ${table}_2018_08 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_08_location4d on ${table}_2018_08 USING GIST (location4d);
CREATE INDEX ${table}_2018_08_location4d_geom_nd on ${table}_2018_08 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_08_info ON ${table}_2018_08 USING GIN (info);

CREATE INDEX ${table}_2018_09_acp_id ON ${table}_2018_09 (acp_id);
CREATE INDEX ${table}_2018_09_acp_lng ON ${table}_2018_09 (acp_lng);
CREATE INDEX ${table}_2018_09_acp_lat ON ${table}_2018_09 (acp_lat);
CREATE INDEX ${table}_2018_09_acp_ts ON ${table}_2018_09 (acp_ts);
CREATE INDEX ${table}_2018_09_location2d on ${table}_2018_09 USING GIST (location2d);
CREATE INDEX ${table}_2018_09_location2d_geom on ${table}_2018_09 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_09_location4d on ${table}_2018_09 USING GIST (location4d);
CREATE INDEX ${table}_2018_09_location4d_geom_nd on ${table}_2018_09 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_09_info ON ${table}_2018_09 USING GIN (info);

CREATE INDEX ${table}_2018_10_acp_id ON ${table}_2018_10 (acp_id);
CREATE INDEX ${table}_2018_10_acp_lng ON ${table}_2018_10 (acp_lng);
CREATE INDEX ${table}_2018_10_acp_lat ON ${table}_2018_10 (acp_lat);
CREATE INDEX ${table}_2018_10_acp_ts ON ${table}_2018_10 (acp_ts);
CREATE INDEX ${table}_2018_10_location2d on ${table}_2018_10 USING GIST (location2d);
CREATE INDEX ${table}_2018_10_location2d_geom on ${table}_2018_10 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_10_location4d on ${table}_2018_10 USING GIST (location4d);
CREATE INDEX ${table}_2018_10_location4d_geom_nd on ${table}_2018_10 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_10_info ON ${table}_2018_10 USING GIN (info);

CREATE INDEX ${table}_2018_11_acp_id ON ${table}_2018_11 (acp_id);
CREATE INDEX ${table}_2018_11_acp_lng ON ${table}_2018_11 (acp_lng);
CREATE INDEX ${table}_2018_11_acp_lat ON ${table}_2018_11 (acp_lat);
CREATE INDEX ${table}_2018_11_acp_ts ON ${table}_2018_11 (acp_ts);
CREATE INDEX ${table}_2018_11_location2d on ${table}_2018_11 USING GIST (location2d);
CREATE INDEX ${table}_2018_11_location2d_geom on ${table}_2018_11 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_11_location4d on ${table}_2018_11 USING GIST (location4d);
CREATE INDEX ${table}_2018_11_location4d_geom_nd on ${table}_2018_11 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_11_info ON ${table}_2018_11 USING GIN (info);

CREATE INDEX ${table}_2018_12_acp_id ON ${table}_2018_12 (acp_id);
CREATE INDEX ${table}_2018_12_acp_lng ON ${table}_2018_12 (acp_lng);
CREATE INDEX ${table}_2018_12_acp_lat ON ${table}_2018_12 (acp_lat);
CREATE INDEX ${table}_2018_12_acp_ts ON ${table}_2018_12 (acp_ts);
CREATE INDEX ${table}_2018_12_location2d on ${table}_2018_12 USING GIST (location2d);
CREATE INDEX ${table}_2018_12_location2d_geom on ${table}_2018_12 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_12_location4d on ${table}_2018_12 USING GIST (location4d);
CREATE INDEX ${table}_2018_12_location4d_geom_nd on ${table}_2018_12 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_12_info ON ${table}_2018_12 USING GIN (info);

CREATE INDEX ${table}_2018_13_acp_id ON ${table}_2018_13 (acp_id);
CREATE INDEX ${table}_2018_13_acp_lng ON ${table}_2018_13 (acp_lng);
CREATE INDEX ${table}_2018_13_acp_lat ON ${table}_2018_13 (acp_lat);
CREATE INDEX ${table}_2018_13_acp_ts ON ${table}_2018_13 (acp_ts);
CREATE INDEX ${table}_2018_13_location2d on ${table}_2018_13 USING GIST (location2d);
CREATE INDEX ${table}_2018_13_location2d_geom on ${table}_2018_13 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_13_location4d on ${table}_2018_13 USING GIST (location4d);
CREATE INDEX ${table}_2018_13_location4d_geom_nd on ${table}_2018_13 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_13_info ON ${table}_2018_13 USING GIN (info);

CREATE INDEX ${table}_2018_14_acp_id ON ${table}_2018_14 (acp_id);
CREATE INDEX ${table}_2018_14_acp_lng ON ${table}_2018_14 (acp_lng);
CREATE INDEX ${table}_2018_14_acp_lat ON ${table}_2018_14 (acp_lat);
CREATE INDEX ${table}_2018_14_acp_ts ON ${table}_2018_14 (acp_ts);
CREATE INDEX ${table}_2018_14_location2d on ${table}_2018_14 USING GIST (location2d);
CREATE INDEX ${table}_2018_14_location2d_geom on ${table}_2018_14 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_14_location4d on ${table}_2018_14 USING GIST (location4d);
CREATE INDEX ${table}_2018_14_location4d_geom_nd on ${table}_2018_14 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_14_info ON ${table}_2018_14 USING GIN (info);

CREATE INDEX ${table}_2018_15_acp_id ON ${table}_2018_15 (acp_id);
CREATE INDEX ${table}_2018_15_acp_lng ON ${table}_2018_15 (acp_lng);
CREATE INDEX ${table}_2018_15_acp_lat ON ${table}_2018_15 (acp_lat);
CREATE INDEX ${table}_2018_15_acp_ts ON ${table}_2018_15 (acp_ts);
CREATE INDEX ${table}_2018_15_location2d on ${table}_2018_15 USING GIST (location2d);
CREATE INDEX ${table}_2018_15_location2d_geom on ${table}_2018_15 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_15_location4d on ${table}_2018_15 USING GIST (location4d);
CREATE INDEX ${table}_2018_15_location4d_geom_nd on ${table}_2018_15 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_15_info ON ${table}_2018_15 USING GIN (info);

CREATE INDEX ${table}_2018_16_acp_id ON ${table}_2018_16 (acp_id);
CREATE INDEX ${table}_2018_16_acp_lng ON ${table}_2018_16 (acp_lng);
CREATE INDEX ${table}_2018_16_acp_lat ON ${table}_2018_16 (acp_lat);
CREATE INDEX ${table}_2018_16_acp_ts ON ${table}_2018_16 (acp_ts);
CREATE INDEX ${table}_2018_16_location2d on ${table}_2018_16 USING GIST (location2d);
CREATE INDEX ${table}_2018_16_location2d_geom on ${table}_2018_16 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_16_location4d on ${table}_2018_16 USING GIST (location4d);
CREATE INDEX ${table}_2018_16_location4d_geom_nd on ${table}_2018_16 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_16_info ON ${table}_2018_16 USING GIN (info);

CREATE INDEX ${table}_2018_17_acp_id ON ${table}_2018_17 (acp_id);
CREATE INDEX ${table}_2018_17_acp_lng ON ${table}_2018_17 (acp_lng);
CREATE INDEX ${table}_2018_17_acp_lat ON ${table}_2018_17 (acp_lat);
CREATE INDEX ${table}_2018_17_acp_ts ON ${table}_2018_17 (acp_ts);
CREATE INDEX ${table}_2018_17_location2d on ${table}_2018_17 USING GIST (location2d);
CREATE INDEX ${table}_2018_17_location2d_geom on ${table}_2018_17 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_17_location4d on ${table}_2018_17 USING GIST (location4d);
CREATE INDEX ${table}_2018_17_location4d_geom_nd on ${table}_2018_17 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_17_info ON ${table}_2018_17 USING GIN (info);

CREATE INDEX ${table}_2018_18_acp_id ON ${table}_2018_18 (acp_id);
CREATE INDEX ${table}_2018_18_acp_lng ON ${table}_2018_18 (acp_lng);
CREATE INDEX ${table}_2018_18_acp_lat ON ${table}_2018_18 (acp_lat);
CREATE INDEX ${table}_2018_18_acp_ts ON ${table}_2018_18 (acp_ts);
CREATE INDEX ${table}_2018_18_location2d on ${table}_2018_18 USING GIST (location2d);
CREATE INDEX ${table}_2018_18_location2d_geom on ${table}_2018_18 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_18_location4d on ${table}_2018_18 USING GIST (location4d);
CREATE INDEX ${table}_2018_18_location4d_geom_nd on ${table}_2018_18 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_18_info ON ${table}_2018_18 USING GIN (info);

CREATE INDEX ${table}_2018_19_acp_id ON ${table}_2018_19 (acp_id);
CREATE INDEX ${table}_2018_19_acp_lng ON ${table}_2018_19 (acp_lng);
CREATE INDEX ${table}_2018_19_acp_lat ON ${table}_2018_19 (acp_lat);
CREATE INDEX ${table}_2018_19_acp_ts ON ${table}_2018_19 (acp_ts);
CREATE INDEX ${table}_2018_19_location2d on ${table}_2018_19 USING GIST (location2d);
CREATE INDEX ${table}_2018_19_location2d_geom on ${table}_2018_19 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_19_location4d on ${table}_2018_19 USING GIST (location4d);
CREATE INDEX ${table}_2018_19_location4d_geom_nd on ${table}_2018_19 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_19_info ON ${table}_2018_19 USING GIN (info);

CREATE INDEX ${table}_2018_20_acp_id ON ${table}_2018_20 (acp_id);
CREATE INDEX ${table}_2018_20_acp_lng ON ${table}_2018_20 (acp_lng);
CREATE INDEX ${table}_2018_20_acp_lat ON ${table}_2018_20 (acp_lat);
CREATE INDEX ${table}_2018_20_acp_ts ON ${table}_2018_20 (acp_ts);
CREATE INDEX ${table}_2018_20_location2d on ${table}_2018_20 USING GIST (location2d);
CREATE INDEX ${table}_2018_20_location2d_geom on ${table}_2018_20 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_20_location4d on ${table}_2018_20 USING GIST (location4d);
CREATE INDEX ${table}_2018_20_location4d_geom_nd on ${table}_2018_20 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_20_info ON ${table}_2018_20 USING GIN (info);

CREATE INDEX ${table}_2018_21_acp_id ON ${table}_2018_21 (acp_id);
CREATE INDEX ${table}_2018_21_acp_lng ON ${table}_2018_21 (acp_lng);
CREATE INDEX ${table}_2018_21_acp_lat ON ${table}_2018_21 (acp_lat);
CREATE INDEX ${table}_2018_21_acp_ts ON ${table}_2018_21 (acp_ts);
CREATE INDEX ${table}_2018_21_location2d on ${table}_2018_21 USING GIST (location2d);
CREATE INDEX ${table}_2018_21_location2d_geom on ${table}_2018_21 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_21_location4d on ${table}_2018_21 USING GIST (location4d);
CREATE INDEX ${table}_2018_21_location4d_geom_nd on ${table}_2018_21 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_21_info ON ${table}_2018_21 USING GIN (info);

CREATE INDEX ${table}_2018_22_acp_id ON ${table}_2018_22 (acp_id);
CREATE INDEX ${table}_2018_22_acp_lng ON ${table}_2018_22 (acp_lng);
CREATE INDEX ${table}_2018_22_acp_lat ON ${table}_2018_22 (acp_lat);
CREATE INDEX ${table}_2018_22_acp_ts ON ${table}_2018_22 (acp_ts);
CREATE INDEX ${table}_2018_22_location2d on ${table}_2018_22 USING GIST (location2d);
CREATE INDEX ${table}_2018_22_location2d_geom on ${table}_2018_22 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_22_location4d on ${table}_2018_22 USING GIST (location4d);
CREATE INDEX ${table}_2018_22_location4d_geom_nd on ${table}_2018_22 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_22_info ON ${table}_2018_22 USING GIN (info);

CREATE INDEX ${table}_2018_23_acp_id ON ${table}_2018_23 (acp_id);
CREATE INDEX ${table}_2018_23_acp_lng ON ${table}_2018_23 (acp_lng);
CREATE INDEX ${table}_2018_23_acp_lat ON ${table}_2018_23 (acp_lat);
CREATE INDEX ${table}_2018_23_acp_ts ON ${table}_2018_23 (acp_ts);
CREATE INDEX ${table}_2018_23_location2d on ${table}_2018_23 USING GIST (location2d);
CREATE INDEX ${table}_2018_23_location2d_geom on ${table}_2018_23 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_23_location4d on ${table}_2018_23 USING GIST (location4d);
CREATE INDEX ${table}_2018_23_location4d_geom_nd on ${table}_2018_23 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_23_info ON ${table}_2018_23 USING GIN (info);

CREATE INDEX ${table}_2018_24_acp_id ON ${table}_2018_24 (acp_id);
CREATE INDEX ${table}_2018_24_acp_lng ON ${table}_2018_24 (acp_lng);
CREATE INDEX ${table}_2018_24_acp_lat ON ${table}_2018_24 (acp_lat);
CREATE INDEX ${table}_2018_24_acp_ts ON ${table}_2018_24 (acp_ts);
CREATE INDEX ${table}_2018_24_location2d on ${table}_2018_24 USING GIST (location2d);
CREATE INDEX ${table}_2018_24_location2d_geom on ${table}_2018_24 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_24_location4d on ${table}_2018_24 USING GIST (location4d);
CREATE INDEX ${table}_2018_24_location4d_geom_nd on ${table}_2018_24 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_24_info ON ${table}_2018_24 USING GIN (info);

CREATE INDEX ${table}_2018_25_acp_id ON ${table}_2018_25 (acp_id);
CREATE INDEX ${table}_2018_25_acp_lng ON ${table}_2018_25 (acp_lng);
CREATE INDEX ${table}_2018_25_acp_lat ON ${table}_2018_25 (acp_lat);
CREATE INDEX ${table}_2018_25_acp_ts ON ${table}_2018_25 (acp_ts);
CREATE INDEX ${table}_2018_25_location2d on ${table}_2018_25 USING GIST (location2d);
CREATE INDEX ${table}_2018_25_location2d_geom on ${table}_2018_25 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_25_location4d on ${table}_2018_25 USING GIST (location4d);
CREATE INDEX ${table}_2018_25_location4d_geom_nd on ${table}_2018_25 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_25_info ON ${table}_2018_25 USING GIN (info);

CREATE INDEX ${table}_2018_26_acp_id ON ${table}_2018_26 (acp_id);
CREATE INDEX ${table}_2018_26_acp_lng ON ${table}_2018_26 (acp_lng);
CREATE INDEX ${table}_2018_26_acp_lat ON ${table}_2018_26 (acp_lat);
CREATE INDEX ${table}_2018_26_acp_ts ON ${table}_2018_26 (acp_ts);
CREATE INDEX ${table}_2018_26_location2d on ${table}_2018_26 USING GIST (location2d);
CREATE INDEX ${table}_2018_26_location2d_geom on ${table}_2018_26 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_26_location4d on ${table}_2018_26 USING GIST (location4d);
CREATE INDEX ${table}_2018_26_location4d_geom_nd on ${table}_2018_26 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_26_info ON ${table}_2018_26 USING GIN (info);

CREATE INDEX ${table}_2018_27_acp_id ON ${table}_2018_27 (acp_id);
CREATE INDEX ${table}_2018_27_acp_lng ON ${table}_2018_27 (acp_lng);
CREATE INDEX ${table}_2018_27_acp_lat ON ${table}_2018_27 (acp_lat);
CREATE INDEX ${table}_2018_27_acp_ts ON ${table}_2018_27 (acp_ts);
CREATE INDEX ${table}_2018_27_location2d on ${table}_2018_27 USING GIST (location2d);
CREATE INDEX ${table}_2018_27_location2d_geom on ${table}_2018_27 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_27_location4d on ${table}_2018_27 USING GIST (location4d);
CREATE INDEX ${table}_2018_27_location4d_geom_nd on ${table}_2018_27 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_27_info ON ${table}_2018_27 USING GIN (info);

CREATE INDEX ${table}_2018_28_acp_id ON ${table}_2018_28 (acp_id);
CREATE INDEX ${table}_2018_28_acp_lng ON ${table}_2018_28 (acp_lng);
CREATE INDEX ${table}_2018_28_acp_lat ON ${table}_2018_28 (acp_lat);
CREATE INDEX ${table}_2018_28_acp_ts ON ${table}_2018_28 (acp_ts);
CREATE INDEX ${table}_2018_28_location2d on ${table}_2018_28 USING GIST (location2d);
CREATE INDEX ${table}_2018_28_location2d_geom on ${table}_2018_28 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_28_location4d on ${table}_2018_28 USING GIST (location4d);
CREATE INDEX ${table}_2018_28_location4d_geom_nd on ${table}_2018_28 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_28_info ON ${table}_2018_28 USING GIN (info);

CREATE INDEX ${table}_2018_29_acp_id ON ${table}_2018_29 (acp_id);
CREATE INDEX ${table}_2018_29_acp_lng ON ${table}_2018_29 (acp_lng);
CREATE INDEX ${table}_2018_29_acp_lat ON ${table}_2018_29 (acp_lat);
CREATE INDEX ${table}_2018_29_acp_ts ON ${table}_2018_29 (acp_ts);
CREATE INDEX ${table}_2018_29_location2d on ${table}_2018_29 USING GIST (location2d);
CREATE INDEX ${table}_2018_29_location2d_geom on ${table}_2018_29 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_29_location4d on ${table}_2018_29 USING GIST (location4d);
CREATE INDEX ${table}_2018_29_location4d_geom_nd on ${table}_2018_29 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_29_info ON ${table}_2018_29 USING GIN (info);

CREATE INDEX ${table}_2018_30_acp_id ON ${table}_2018_30 (acp_id);
CREATE INDEX ${table}_2018_30_acp_lng ON ${table}_2018_30 (acp_lng);
CREATE INDEX ${table}_2018_30_acp_lat ON ${table}_2018_30 (acp_lat);
CREATE INDEX ${table}_2018_30_acp_ts ON ${table}_2018_30 (acp_ts);
CREATE INDEX ${table}_2018_30_location2d on ${table}_2018_30 USING GIST (location2d);
CREATE INDEX ${table}_2018_30_location2d_geom on ${table}_2018_30 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_30_location4d on ${table}_2018_30 USING GIST (location4d);
CREATE INDEX ${table}_2018_30_location4d_geom_nd on ${table}_2018_30 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_30_info ON ${table}_2018_30 USING GIN (info);

CREATE INDEX ${table}_2018_31_acp_id ON ${table}_2018_31 (acp_id);
CREATE INDEX ${table}_2018_31_acp_lng ON ${table}_2018_31 (acp_lng);
CREATE INDEX ${table}_2018_31_acp_lat ON ${table}_2018_31 (acp_lat);
CREATE INDEX ${table}_2018_31_acp_ts ON ${table}_2018_31 (acp_ts);
CREATE INDEX ${table}_2018_31_location2d on ${table}_2018_31 USING GIST (location2d);
CREATE INDEX ${table}_2018_31_location2d_geom on ${table}_2018_31 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_31_location4d on ${table}_2018_31 USING GIST (location4d);
CREATE INDEX ${table}_2018_31_location4d_geom_nd on ${table}_2018_31 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_31_info ON ${table}_2018_31 USING GIN (info);

CREATE INDEX ${table}_2018_32_acp_id ON ${table}_2018_32 (acp_id);
CREATE INDEX ${table}_2018_32_acp_lng ON ${table}_2018_32 (acp_lng);
CREATE INDEX ${table}_2018_32_acp_lat ON ${table}_2018_32 (acp_lat);
CREATE INDEX ${table}_2018_32_acp_ts ON ${table}_2018_32 (acp_ts);
CREATE INDEX ${table}_2018_32_location2d on ${table}_2018_32 USING GIST (location2d);
CREATE INDEX ${table}_2018_32_location2d_geom on ${table}_2018_32 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_32_location4d on ${table}_2018_32 USING GIST (location4d);
CREATE INDEX ${table}_2018_32_location4d_geom_nd on ${table}_2018_32 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_32_info ON ${table}_2018_32 USING GIN (info);

CREATE INDEX ${table}_2018_33_acp_id ON ${table}_2018_33 (acp_id);
CREATE INDEX ${table}_2018_33_acp_lng ON ${table}_2018_33 (acp_lng);
CREATE INDEX ${table}_2018_33_acp_lat ON ${table}_2018_33 (acp_lat);
CREATE INDEX ${table}_2018_33_acp_ts ON ${table}_2018_33 (acp_ts);
CREATE INDEX ${table}_2018_33_location2d on ${table}_2018_33 USING GIST (location2d);
CREATE INDEX ${table}_2018_33_location2d_geom on ${table}_2018_33 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_33_location4d on ${table}_2018_33 USING GIST (location4d);
CREATE INDEX ${table}_2018_33_location4d_geom_nd on ${table}_2018_33 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_33_info ON ${table}_2018_33 USING GIN (info);

CREATE INDEX ${table}_2018_34_acp_id ON ${table}_2018_34 (acp_id);
CREATE INDEX ${table}_2018_34_acp_lng ON ${table}_2018_34 (acp_lng);
CREATE INDEX ${table}_2018_34_acp_lat ON ${table}_2018_34 (acp_lat);
CREATE INDEX ${table}_2018_34_acp_ts ON ${table}_2018_34 (acp_ts);
CREATE INDEX ${table}_2018_34_location2d on ${table}_2018_34 USING GIST (location2d);
CREATE INDEX ${table}_2018_34_location2d_geom on ${table}_2018_34 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_34_location4d on ${table}_2018_34 USING GIST (location4d);
CREATE INDEX ${table}_2018_34_location4d_geom_nd on ${table}_2018_34 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_34_info ON ${table}_2018_34 USING GIN (info);

CREATE INDEX ${table}_2018_35_acp_id ON ${table}_2018_35 (acp_id);
CREATE INDEX ${table}_2018_35_acp_lng ON ${table}_2018_35 (acp_lng);
CREATE INDEX ${table}_2018_35_acp_lat ON ${table}_2018_35 (acp_lat);
CREATE INDEX ${table}_2018_35_acp_ts ON ${table}_2018_35 (acp_ts);
CREATE INDEX ${table}_2018_35_location2d on ${table}_2018_35 USING GIST (location2d);
CREATE INDEX ${table}_2018_35_location2d_geom on ${table}_2018_35 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_35_location4d on ${table}_2018_35 USING GIST (location4d);
CREATE INDEX ${table}_2018_35_location4d_geom_nd on ${table}_2018_35 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_35_info ON ${table}_2018_35 USING GIN (info);

CREATE INDEX ${table}_2018_36_acp_id ON ${table}_2018_36 (acp_id);
CREATE INDEX ${table}_2018_36_acp_lng ON ${table}_2018_36 (acp_lng);
CREATE INDEX ${table}_2018_36_acp_lat ON ${table}_2018_36 (acp_lat);
CREATE INDEX ${table}_2018_36_acp_ts ON ${table}_2018_36 (acp_ts);
CREATE INDEX ${table}_2018_36_location2d on ${table}_2018_36 USING GIST (location2d);
CREATE INDEX ${table}_2018_36_location2d_geom on ${table}_2018_36 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_36_location4d on ${table}_2018_36 USING GIST (location4d);
CREATE INDEX ${table}_2018_36_location4d_geom_nd on ${table}_2018_36 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_36_info ON ${table}_2018_36 USING GIN (info);

CREATE INDEX ${table}_2018_37_acp_id ON ${table}_2018_37 (acp_id);
CREATE INDEX ${table}_2018_37_acp_lng ON ${table}_2018_37 (acp_lng);
CREATE INDEX ${table}_2018_37_acp_lat ON ${table}_2018_37 (acp_lat);
CREATE INDEX ${table}_2018_37_acp_ts ON ${table}_2018_37 (acp_ts);
CREATE INDEX ${table}_2018_37_location2d on ${table}_2018_37 USING GIST (location2d);
CREATE INDEX ${table}_2018_37_location2d_geom on ${table}_2018_37 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_37_location4d on ${table}_2018_37 USING GIST (location4d);
CREATE INDEX ${table}_2018_37_location4d_geom_nd on ${table}_2018_37 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_37_info ON ${table}_2018_37 USING GIN (info);

CREATE INDEX ${table}_2018_38_acp_id ON ${table}_2018_38 (acp_id);
CREATE INDEX ${table}_2018_38_acp_lng ON ${table}_2018_38 (acp_lng);
CREATE INDEX ${table}_2018_38_acp_lat ON ${table}_2018_38 (acp_lat);
CREATE INDEX ${table}_2018_38_acp_ts ON ${table}_2018_38 (acp_ts);
CREATE INDEX ${table}_2018_38_location2d on ${table}_2018_38 USING GIST (location2d);
CREATE INDEX ${table}_2018_38_location2d_geom on ${table}_2018_38 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_38_location4d on ${table}_2018_38 USING GIST (location4d);
CREATE INDEX ${table}_2018_38_location4d_geom_nd on ${table}_2018_38 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_38_info ON ${table}_2018_38 USING GIN (info);

CREATE INDEX ${table}_2018_39_acp_id ON ${table}_2018_39 (acp_id);
CREATE INDEX ${table}_2018_39_acp_lng ON ${table}_2018_39 (acp_lng);
CREATE INDEX ${table}_2018_39_acp_lat ON ${table}_2018_39 (acp_lat);
CREATE INDEX ${table}_2018_39_acp_ts ON ${table}_2018_39 (acp_ts);
CREATE INDEX ${table}_2018_39_location2d on ${table}_2018_39 USING GIST (location2d);
CREATE INDEX ${table}_2018_39_location2d_geom on ${table}_2018_39 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_39_location4d on ${table}_2018_39 USING GIST (location4d);
CREATE INDEX ${table}_2018_39_location4d_geom_nd on ${table}_2018_39 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_39_info ON ${table}_2018_39 USING GIN (info);

CREATE INDEX ${table}_2018_40_acp_id ON ${table}_2018_40 (acp_id);
CREATE INDEX ${table}_2018_40_acp_lng ON ${table}_2018_40 (acp_lng);
CREATE INDEX ${table}_2018_40_acp_lat ON ${table}_2018_40 (acp_lat);
CREATE INDEX ${table}_2018_40_acp_ts ON ${table}_2018_40 (acp_ts);
CREATE INDEX ${table}_2018_40_location2d on ${table}_2018_40 USING GIST (location2d);
CREATE INDEX ${table}_2018_40_location2d_geom on ${table}_2018_40 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_40_location4d on ${table}_2018_40 USING GIST (location4d);
CREATE INDEX ${table}_2018_40_location4d_geom_nd on ${table}_2018_40 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_40_info ON ${table}_2018_40 USING GIN (info);

CREATE INDEX ${table}_2018_41_acp_id ON ${table}_2018_41 (acp_id);
CREATE INDEX ${table}_2018_41_acp_lng ON ${table}_2018_41 (acp_lng);
CREATE INDEX ${table}_2018_41_acp_lat ON ${table}_2018_41 (acp_lat);
CREATE INDEX ${table}_2018_41_acp_ts ON ${table}_2018_41 (acp_ts);
CREATE INDEX ${table}_2018_41_location2d on ${table}_2018_41 USING GIST (location2d);
CREATE INDEX ${table}_2018_41_location2d_geom on ${table}_2018_41 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_41_location4d on ${table}_2018_41 USING GIST (location4d);
CREATE INDEX ${table}_2018_41_location4d_geom_nd on ${table}_2018_41 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_41_info ON ${table}_2018_41 USING GIN (info);

CREATE INDEX ${table}_2018_42_acp_id ON ${table}_2018_42 (acp_id);
CREATE INDEX ${table}_2018_42_acp_lng ON ${table}_2018_42 (acp_lng);
CREATE INDEX ${table}_2018_42_acp_lat ON ${table}_2018_42 (acp_lat);
CREATE INDEX ${table}_2018_42_acp_ts ON ${table}_2018_42 (acp_ts);
CREATE INDEX ${table}_2018_42_location2d on ${table}_2018_42 USING GIST (location2d);
CREATE INDEX ${table}_2018_42_location2d_geom on ${table}_2018_42 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_42_location4d on ${table}_2018_42 USING GIST (location4d);
CREATE INDEX ${table}_2018_42_location4d_geom_nd on ${table}_2018_42 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_42_info ON ${table}_2018_42 USING GIN (info);

CREATE INDEX ${table}_2018_43_acp_id ON ${table}_2018_43 (acp_id);
CREATE INDEX ${table}_2018_43_acp_lng ON ${table}_2018_43 (acp_lng);
CREATE INDEX ${table}_2018_43_acp_lat ON ${table}_2018_43 (acp_lat);
CREATE INDEX ${table}_2018_43_acp_ts ON ${table}_2018_43 (acp_ts);
CREATE INDEX ${table}_2018_43_location2d on ${table}_2018_43 USING GIST (location2d);
CREATE INDEX ${table}_2018_43_location2d_geom on ${table}_2018_43 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_43_location4d on ${table}_2018_43 USING GIST (location4d);
CREATE INDEX ${table}_2018_43_location4d_geom_nd on ${table}_2018_43 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_43_info ON ${table}_2018_43 USING GIN (info);

CREATE INDEX ${table}_2018_44_acp_id ON ${table}_2018_44 (acp_id);
CREATE INDEX ${table}_2018_44_acp_lng ON ${table}_2018_44 (acp_lng);
CREATE INDEX ${table}_2018_44_acp_lat ON ${table}_2018_44 (acp_lat);
CREATE INDEX ${table}_2018_44_acp_ts ON ${table}_2018_44 (acp_ts);
CREATE INDEX ${table}_2018_44_location2d on ${table}_2018_44 USING GIST (location2d);
CREATE INDEX ${table}_2018_44_location2d_geom on ${table}_2018_44 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_44_location4d on ${table}_2018_44 USING GIST (location4d);
CREATE INDEX ${table}_2018_44_location4d_geom_nd on ${table}_2018_44 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_44_info ON ${table}_2018_44 USING GIN (info);

CREATE INDEX ${table}_2018_45_acp_id ON ${table}_2018_45 (acp_id);
CREATE INDEX ${table}_2018_45_acp_lng ON ${table}_2018_45 (acp_lng);
CREATE INDEX ${table}_2018_45_acp_lat ON ${table}_2018_45 (acp_lat);
CREATE INDEX ${table}_2018_45_acp_ts ON ${table}_2018_45 (acp_ts);
CREATE INDEX ${table}_2018_45_location2d on ${table}_2018_45 USING GIST (location2d);
CREATE INDEX ${table}_2018_45_location2d_geom on ${table}_2018_45 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_45_location4d on ${table}_2018_45 USING GIST (location4d);
CREATE INDEX ${table}_2018_45_location4d_geom_nd on ${table}_2018_45 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_45_info ON ${table}_2018_45 USING GIN (info);

CREATE INDEX ${table}_2018_46_acp_id ON ${table}_2018_46 (acp_id);
CREATE INDEX ${table}_2018_46_acp_lng ON ${table}_2018_46 (acp_lng);
CREATE INDEX ${table}_2018_46_acp_lat ON ${table}_2018_46 (acp_lat);
CREATE INDEX ${table}_2018_46_acp_ts ON ${table}_2018_46 (acp_ts);
CREATE INDEX ${table}_2018_46_location2d on ${table}_2018_46 USING GIST (location2d);
CREATE INDEX ${table}_2018_46_location2d_geom on ${table}_2018_46 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_46_location4d on ${table}_2018_46 USING GIST (location4d);
CREATE INDEX ${table}_2018_46_location4d_geom_nd on ${table}_2018_46 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_46_info ON ${table}_2018_46 USING GIN (info);

CREATE INDEX ${table}_2018_47_acp_id ON ${table}_2018_47 (acp_id);
CREATE INDEX ${table}_2018_47_acp_lng ON ${table}_2018_47 (acp_lng);
CREATE INDEX ${table}_2018_47_acp_lat ON ${table}_2018_47 (acp_lat);
CREATE INDEX ${table}_2018_47_acp_ts ON ${table}_2018_47 (acp_ts);
CREATE INDEX ${table}_2018_47_location2d on ${table}_2018_47 USING GIST (location2d);
CREATE INDEX ${table}_2018_47_location2d_geom on ${table}_2018_47 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_47_location4d on ${table}_2018_47 USING GIST (location4d);
CREATE INDEX ${table}_2018_47_location4d_geom_nd on ${table}_2018_47 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_47_info ON ${table}_2018_47 USING GIN (info);

CREATE INDEX ${table}_2018_48_acp_id ON ${table}_2018_48 (acp_id);
CREATE INDEX ${table}_2018_48_acp_lng ON ${table}_2018_48 (acp_lng);
CREATE INDEX ${table}_2018_48_acp_lat ON ${table}_2018_48 (acp_lat);
CREATE INDEX ${table}_2018_48_acp_ts ON ${table}_2018_48 (acp_ts);
CREATE INDEX ${table}_2018_48_location2d on ${table}_2018_48 USING GIST (location2d);
CREATE INDEX ${table}_2018_48_location2d_geom on ${table}_2018_48 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_48_location4d on ${table}_2018_48 USING GIST (location4d);
CREATE INDEX ${table}_2018_48_location4d_geom_nd on ${table}_2018_48 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_48_info ON ${table}_2018_48 USING GIN (info);

CREATE INDEX ${table}_2018_49_acp_id ON ${table}_2018_49 (acp_id);
CREATE INDEX ${table}_2018_49_acp_lng ON ${table}_2018_49 (acp_lng);
CREATE INDEX ${table}_2018_49_acp_lat ON ${table}_2018_49 (acp_lat);
CREATE INDEX ${table}_2018_49_acp_ts ON ${table}_2018_49 (acp_ts);
CREATE INDEX ${table}_2018_49_location2d on ${table}_2018_49 USING GIST (location2d);
CREATE INDEX ${table}_2018_49_location2d_geom on ${table}_2018_49 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_49_location4d on ${table}_2018_49 USING GIST (location4d);
CREATE INDEX ${table}_2018_49_location4d_geom_nd on ${table}_2018_49 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_49_info ON ${table}_2018_49 USING GIN (info);

CREATE INDEX ${table}_2018_50_acp_id ON ${table}_2018_50 (acp_id);
CREATE INDEX ${table}_2018_50_acp_lng ON ${table}_2018_50 (acp_lng);
CREATE INDEX ${table}_2018_50_acp_lat ON ${table}_2018_50 (acp_lat);
CREATE INDEX ${table}_2018_50_acp_ts ON ${table}_2018_50 (acp_ts);
CREATE INDEX ${table}_2018_50_location2d on ${table}_2018_50 USING GIST (location2d);
CREATE INDEX ${table}_2018_50_location2d_geom on ${table}_2018_50 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_50_location4d on ${table}_2018_50 USING GIST (location4d);
CREATE INDEX ${table}_2018_50_location4d_geom_nd on ${table}_2018_50 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_50_info ON ${table}_2018_50 USING GIN (info);

CREATE INDEX ${table}_2018_51_acp_id ON ${table}_2018_51 (acp_id);
CREATE INDEX ${table}_2018_51_acp_lng ON ${table}_2018_51 (acp_lng);
CREATE INDEX ${table}_2018_51_acp_lat ON ${table}_2018_51 (acp_lat);
CREATE INDEX ${table}_2018_51_acp_ts ON ${table}_2018_51 (acp_ts);
CREATE INDEX ${table}_2018_51_location2d on ${table}_2018_51 USING GIST (location2d);
CREATE INDEX ${table}_2018_51_location2d_geom on ${table}_2018_51 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_51_location4d on ${table}_2018_51 USING GIST (location4d);
CREATE INDEX ${table}_2018_51_location4d_geom_nd on ${table}_2018_51 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_51_info ON ${table}_2018_51 USING GIN (info);

CREATE INDEX ${table}_2018_52_acp_id ON ${table}_2018_52 (acp_id);
CREATE INDEX ${table}_2018_52_acp_lng ON ${table}_2018_52 (acp_lng);
CREATE INDEX ${table}_2018_52_acp_lat ON ${table}_2018_52 (acp_lat);
CREATE INDEX ${table}_2018_52_acp_ts ON ${table}_2018_52 (acp_ts);
CREATE INDEX ${table}_2018_52_location2d on ${table}_2018_52 USING GIST (location2d);
CREATE INDEX ${table}_2018_52_location2d_geom on ${table}_2018_52 USING GIST (cast(location2d as geometry));
CREATE INDEX ${table}_2018_52_location4d on ${table}_2018_52 USING GIST (location4d);
CREATE INDEX ${table}_2018_52_location4d_geom_nd on ${table}_2018_52 USING GIST (cast(location4d as geometry) gist_geometry_ops_nd);
CREATE INDEX ${table}_2018_52_info ON ${table}_2018_52 USING GIN (info);




-- ---------------------------------------------------------------------
-- END AUTO GENERATED SECTION
-- ---------------------------------------------------------------------

COMMIT;

EOF

